################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
core/mllite/data_builder.obj: ../core/mllite/data_builder.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/data_builder.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/hal_outputs.obj: ../core/mllite/hal_outputs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/hal_outputs.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/message_layer.obj: ../core/mllite/message_layer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/message_layer.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/ml_math_func.obj: ../core/mllite/ml_math_func.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/ml_math_func.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/mlmath.obj: ../core/mllite/mlmath.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/mlmath.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/mpl.obj: ../core/mllite/mpl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/mpl.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/results_holder.obj: ../core/mllite/results_holder.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/results_holder.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/start_manager.obj: ../core/mllite/start_manager.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/start_manager.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

core/mllite/storage_manager.obj: ../core/mllite/storage_manager.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="core/mllite/storage_manager.pp" --obj_directory="core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


