################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
driverlib/MSP430F5xx_6xx/adc10_a.obj: ../driverlib/MSP430F5xx_6xx/adc10_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/adc10_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/adc12_a.obj: ../driverlib/MSP430F5xx_6xx/adc12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/adc12_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/aes.obj: ../driverlib/MSP430F5xx_6xx/aes.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/aes.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/battbak.obj: ../driverlib/MSP430F5xx_6xx/battbak.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/battbak.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/comp_b.obj: ../driverlib/MSP430F5xx_6xx/comp_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/comp_b.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/crc.obj: ../driverlib/MSP430F5xx_6xx/crc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/crc.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/ctsd16.obj: ../driverlib/MSP430F5xx_6xx/ctsd16.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/ctsd16.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/dac12_a.obj: ../driverlib/MSP430F5xx_6xx/dac12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/dac12_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/dma.obj: ../driverlib/MSP430F5xx_6xx/dma.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/dma.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/eusci_a_spi.obj: ../driverlib/MSP430F5xx_6xx/eusci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/eusci_a_spi.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/eusci_a_uart.obj: ../driverlib/MSP430F5xx_6xx/eusci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/eusci_a_uart.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/eusci_b_i2c.obj: ../driverlib/MSP430F5xx_6xx/eusci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/eusci_b_i2c.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/eusci_b_spi.obj: ../driverlib/MSP430F5xx_6xx/eusci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/eusci_b_spi.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/flashctl.obj: ../driverlib/MSP430F5xx_6xx/flashctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/flashctl.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/gpio.obj: ../driverlib/MSP430F5xx_6xx/gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/gpio.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/lcd_b.obj: ../driverlib/MSP430F5xx_6xx/lcd_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/lcd_b.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/ldopwr.obj: ../driverlib/MSP430F5xx_6xx/ldopwr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/ldopwr.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/mpy32.obj: ../driverlib/MSP430F5xx_6xx/mpy32.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/mpy32.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/oa.obj: ../driverlib/MSP430F5xx_6xx/oa.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/oa.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/pmap.obj: ../driverlib/MSP430F5xx_6xx/pmap.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/pmap.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/pmm.obj: ../driverlib/MSP430F5xx_6xx/pmm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/pmm.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/ram.obj: ../driverlib/MSP430F5xx_6xx/ram.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/ram.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/ref.obj: ../driverlib/MSP430F5xx_6xx/ref.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/ref.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/rtc_a.obj: ../driverlib/MSP430F5xx_6xx/rtc_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/rtc_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/rtc_b.obj: ../driverlib/MSP430F5xx_6xx/rtc_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/rtc_b.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/rtc_c.obj: ../driverlib/MSP430F5xx_6xx/rtc_c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/rtc_c.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/sd24_b.obj: ../driverlib/MSP430F5xx_6xx/sd24_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/sd24_b.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/sfr.obj: ../driverlib/MSP430F5xx_6xx/sfr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/sfr.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/sysctl.obj: ../driverlib/MSP430F5xx_6xx/sysctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/sysctl.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/tec.obj: ../driverlib/MSP430F5xx_6xx/tec.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/tec.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/timer_a.obj: ../driverlib/MSP430F5xx_6xx/timer_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/timer_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/timer_b.obj: ../driverlib/MSP430F5xx_6xx/timer_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/timer_b.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/timer_d.obj: ../driverlib/MSP430F5xx_6xx/timer_d.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/timer_d.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/tlv.obj: ../driverlib/MSP430F5xx_6xx/tlv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/tlv.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/ucs.obj: ../driverlib/MSP430F5xx_6xx/ucs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/ucs.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/usci_a_spi.obj: ../driverlib/MSP430F5xx_6xx/usci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/usci_a_spi.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/usci_a_uart.obj: ../driverlib/MSP430F5xx_6xx/usci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/usci_a_uart.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/usci_b_i2c.obj: ../driverlib/MSP430F5xx_6xx/usci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/usci_b_i2c.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/usci_b_spi.obj: ../driverlib/MSP430F5xx_6xx/usci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/usci_b_spi.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

driverlib/MSP430F5xx_6xx/wdt_a.obj: ../driverlib/MSP430F5xx_6xx/wdt_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/bin/cl430" -vmspx --abi=coffabi --code_model=large --data_model=restricted --near_data=globals -O0 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccsv6/ccs_base/msp430/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.5/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/eMPL" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/include" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430" --include_path="C:/Users/harper/workspace_v6_1/boat/core/driver/msp430/F5xx_F6xx_Core_Lib" --include_path="C:/Users/harper/workspace_v6_1/boat/core/eMPL-hal" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mllite" --include_path="C:/Users/harper/workspace_v6_1/boat/core/mpl" --include_path="C:/Users/harper/workspace_v6_1/boat/app/MSP430" --include_path="C:/Users/harper/workspace_v6_1/boat/driverlib/MSP430F5xx_6xx" -g --gcc --define=USE_DMP --define=MPU9150 --define=I2C_B0 --define=EMPL --define=EMPL_TARGET_MSP430 --define=__MSP430F5529__ --display_error_number --diag_warning=225 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="driverlib/MSP430F5xx_6xx/wdt_a.pp" --obj_directory="driverlib/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


